### ISSUE TITLE
Locate V2 launch

### ISSUE THREAD

**Issue by cristinaleonr** [m-lab/locate#102]
This launch will update the Locate Service to serve /v2/nearest requests through the Locate V2 (not using mlab-ns as a proxy).

**Steps:**
- [x] Add `locate_version` parameter to the generated URLs.
- [x] Add healthy server count metrics to the Locate V2 for comparisons.
- [x] Discuss launch plan with the team.
- [x] Add Grafana dashboard to compare Locate V2 to mlab-ns.
- [x] Update `v2/nearest/` requests to go through the Locate V2 and change the build configuration not to promote the latest deployed version to receive 100% of traffic.
- [x] Release the latest version to 5% of traffic for one week 
- [x] Confirm that the rollout dashboard looks as expected, and release the latest version to 10% of traffic for one week
- [x] Confirm that the rollout dashboard looks as expected, and release the latest version to 25% of traffic for one week
- [x] Confirm that the rollout dashboard looks as expected, and release the latest version to 50% of traffic for one week
- [x] Confirm that the rollout dashboard looks as expected, and release the latest version to 100% of traffic for one week

**Rollout dashboard:**
https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5m

**Criteria before progressing:**
- The difference in healthy server counts between the Locate and mlab-ns in the dashboard is no more than 5%.
- The distribution of the number of tests per site in the dashboard match the probabilities defined in the [config](https://github.com/m-lab/locate/blob/main/static/configs.go#L85).
- The number of tests per machine in the dashboard follow the same distribution for the Locate and mlab-ns (e.g., if there is a machine that is receiving reduced or no traffic, it will be reflected in both versions).
- [Global test rates](https://grafana.mlab-sandbox.measurementlab.net/d/Cyq7WeNiz/ndt-global-test-rate?orgId=1) are unaffected. 
- No alerts are firing due to the rollout.

**Rollback criteria:**
- If there is any change to the global test rates or any alerts that fire due to the rollout, we should immediately roll back.
- If any of the dashboard panels does not match the expectations described above, we should consider rolling back.

**Things we expect to change:**
- The platform-type query will not require an API Key through the `/v2/nearest/` path.
- Clients using the `v2beta2` path will have to be migrated to the `v2/nearest/` path.
- In-country biasing will be added back after the launch is complete.

**Comment by stephen-soltesz** [comment]
Discussed recently and at ops-tactical this morning:
* We observed last week that the server selection algorithm is based on index of a sorted list rather than on distance. The net effect of this is that users in regions with many sites see smaller distance deltas than users in regions with fewer sites. One index difference could mean the difference in 1000's of kms.
* The main priority is to migrate off of mlab-ns, not necessarily to add new functionality (e.g. probabilistic server selection). Maintaining feature parity with mlab-ns (strictly nearest server to client) is still an option.
* We see greater distances for some regions than others, (e.g. Oceania vs North America), but do not know if this is performance impacting for users based on distances alone.
* Before rolling back the current server selection method in Locate v2, we want to assess whether there is any evident difference in the distribution of performance for users to their selected servers.
* @laiyi-ohlsen will look at regional performance distributions and we'll assess based on those before we continue the rollout to 10%.

**Comment by cristinaleonr** [comment]
@laiyi-ohlsen created a [colab](https://colab.research.google.com/drive/1XbA4bA1IsNOjTsJzSLvjb5naZzCBTNIB?authuser=1) to compare regional performance distributions before the rollout (as a control group), after the rollout for mlab-ns traffic, and after the rollout for Locate v2 traffic.

Specifically, comparisons at the continent level show that performance seems comparable across the 3 versions. 
![image](https://user-images.githubusercontent.com/21001496/208990611-a9bea10d-2c95-446f-8bec-9d4b878b7142.png)

The rollout has been increased to 10% to gather more data and evaluate again.

**Comment by cristinaleonr** [comment]
Regional performance distributions before the rollout (Th 12/08 and Fr 12/09) and after the increase to 10% (Th 12/22 and Fr 12/23) don't reflect any noticeable differences. We will proceed with the increase to 25%.

![locatev2-analysis_before5-after10_continents_v2](https://user-images.githubusercontent.com/21001496/211873342-3cfa5190-f95b-4204-a458-bcb743c9d959.png)

**Comment by cristinaleonr** [comment]
Regional performance distributions before the rollout (Th 12/08 and Fr 12/09) and after the increase to 25% (Th 01/12 and Fr 01/13) only reflect a slight performance difference in AF (which has been observed in the past). 

![locatev2-analysis_before5-after25_continents](https://user-images.githubusercontent.com/21001496/214598898-335fa535-a1fe-4567-ac5f-c57bf3fcbbf8.png)

On 01/19, it was discovered that between 1-2% of /nearest requests to the V2 version were getting 500 errors. 

![Screenshot 2023-01-25 10 14 19 AM](https://user-images.githubusercontent.com/21001496/214600846-645c5684-4f82-463a-b235-932a8ed14ecc.png)

The errors were traced back to a race condition that was causing the Locate Service to panic and crash.
```
DEFAULT 2023-01-19T14:45:31Z fatal error: concurrent map iteration and map write
DEFAULT 2023-01-19T14:45:31Z
DEFAULT 2023-01-19T14:45:31Z goroutine 3477 [running]:
DEFAULT 2023-01-19T14:45:31Z runtime.throw({0xd13b91?, 0xe6?})
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000281720 sp=0xc0002816f0 pc=0x439ed1
DEFAULT 2023-01-19T14:45:31Z runtime.mapiternext(0xbcb4e0?)
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/runtime/map.go:871 +0x4eb fp=0xc000281790 sp=0xc000281720 pc=0x411bab
DEFAULT 2023-01-19T14:45:31Z github.com/m-lab/locate/heartbeat.(*heartbeatStatusTracker).Instances(0xc00017e040)
DEFAULT 2023-01-19T14:45:31Z /go/src/github.com/m-lab/locate/heartbeat/heartbeat.go:107 +0x99 fp=0xc000281840 sp=0xc000281790 pc=0xa98959
DEFAULT 2023-01-19T14:45:31Z github.com/m-lab/locate/heartbeat.(*Locator).Nearest(0xc004cb4870?, {0xc0000404f8, 0x8}, 0xc?, 0xc0001fe930?, 0x6cf100?)
DEFAULT 2023-01-19T14:45:31Z /go/src/github.com/m-lab/locate/heartbeat/location.go:67 +0x43 fp=0xc0002818b0 sp=0xc000281840 pc=0xa997a3
DEFAULT 2023-01-19T14:45:31Z github.com/m-lab/locate/handler.(*Client).Nearest(0xc00036c150, {0xe21220, 0xc00037e0e0}, 0xc004003000)
DEFAULT 2023-01-19T14:45:31Z /go/src/github.com/m-lab/locate/handler/handler.go:196 +0x54a fp=0xc0002819f0 sp=0xc0002818b0 pc=0xb0d0ca
DEFAULT 2023-01-19T14:45:31Z github.com/m-lab/locate/handler.(*Client).Nearest-fm({0xe21220?, 0xc00037e0e0?}, 0x0?)
DEFAULT 2023-01-19T14:45:31Z <autogenerated>:1 +0x3c fp=0xc000281a20 sp=0xc0002819f0 pc=0xb163fc
DEFAULT 2023-01-19T14:45:31Z net/http.HandlerFunc.ServeHTTP(0x7fd1e4c41758?, {0xe21220?, 0xc00037e0e0?}, 0x40f1a5?)
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc000281a48 sp=0xc000281a20 pc=0x6cd90f
DEFAULT 2023-01-19T14:45:31Z net/http.(*ServeMux).ServeHTTP(0xc004138259?, {0xe21220, 0xc00037e0e0}, 0xc004003000)
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/net/http/server.go:2462 +0x149 fp=0xc000281a98 sp=0xc000281a48 pc=0x6cf2a9
DEFAULT 2023-01-19T14:45:31Z net/http.serverHandler.ServeHTTP({0xc0045053b0?}, {0xe21220, 0xc00037e0e0}, 0xc004003000)
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/net/http/server.go:2916 +0x43b fp=0xc000281b58 sp=0xc000281a98 pc=0x6d0efb
DEFAULT 2023-01-19T14:45:31Z net/http.(*conn).serve(0xc000d37180, {0xe21d48, 0xc000129e90})
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/net/http/server.go:1966 +0x5d7 fp=0xc000281fb8 sp=0xc000281b58 pc=0x6cc3b7
DEFAULT 2023-01-19T14:45:31Z net/http.(*Server).Serve.func3()
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/net/http/server.go:3071 +0x2e fp=0xc000281fe0 sp=0xc000281fb8 pc=0x6d184e
DEFAULT 2023-01-19T14:45:31Z runtime.goexit()
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000281fe8 sp=0xc000281fe0 pc=0x46c641
DEFAULT 2023-01-19T14:45:31Z created by net/http.(*Server).Serve
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/net/http/server.go:3071 +0x4db
```

A fix (https://github.com/m-lab/locate/pull/108) was developed and released on 01/20. Alerts (https://github.com/m-lab/prometheus-support/pull/968) were also added to automatically catch these types of scenarios in the future. 

The error rate is now 0%.

![Screenshot 2023-01-25 10 13 48 AM](https://user-images.githubusercontent.com/21001496/214600659-9d03564e-2efb-4803-bdcd-5ec718b657c9.png)

**Comment by cristinaleonr** [comment]
The [Locate_TooManyErrors](https://github.com/m-lab/prometheus-support/blob/3399465f5d33b04dc01f71e34f27c9eb686e2072/config/federation/prometheus/alerts.yml#L586) alert fired for 5 minutes on 01/25.

The errors came from a single instance that had just been created and appeared not ready to serve requests yet.

![Screenshot 2023-02-03 1 28 32 PM](https://user-images.githubusercontent.com/21001496/216679708-79cf1e95-5ae1-4c87-9477-333610efd946.png)

Further looking into why this instance had just been created, it was discovered App Engine often upscales and downscales Locate V2 instances.

![Screenshot 2023-02-03 1 31 37 PM](https://user-images.githubusercontent.com/21001496/216680530-3e405619-cd44-4ac4-9846-c2c750548cce.png)

The same behavior was observed even after [changing](https://github.com/m-lab/locate/pull/109) the Locate's scaling configuration to target a lower CPU usage target for scaling, so the scaling configuration change was [reverted](https://github.com/m-lab/locate/pull/111) and more metrics were added to provide more insight into why a newly create instance would fail to serve successful `/nearest` requests on start.

**Comment by cristinaleonr** [comment]
Regional test performance distributions show no noticeable performance difference between the v2 and v2_proxy versions after the traffic increase to 50%.

![locatev2-analysis_after25-after50_continents_afteronly](https://user-images.githubusercontent.com/21001496/217063988-70f1695d-86bd-4d34-b233-31e989bbb585.png)

Both the v2 and v2_proxy versions show small performance differences with respect to the version before the rollout (December 2022), which can be expected given the amount of time that has passed.
![locatev2-analysis_before5-after50_continents](https://user-images.githubusercontent.com/21001496/217064856-049603d8-1c9f-4059-884a-1128c1668b85.png)

The traffic allocation for the Locate V2 has now been increased to 100%.
