### ISSUE TITLE
Add handler for SIGTERM to heartbeat

### ISSUE THREAD

**Issue by nkinkade** [m-lab/locate#138]
When the heartbeat service receives a SIGTERM from the OS, it should send an unhealthy signal to Locate before exiting. [Pusher implements this sort of handling](https://github.com/m-lab/pusher/blob/main/pusher.go#L170), for example, so that we lose as little data as possible (or even none) on shutdown/reboot events.

Today, as I understand it, Locate will automatically flag a service as down if it doesn't receive a signal from heartbeat for more than 30s. If a machine gets rebooted or otherwise the heartbeat service gets terminated, there could be up to 30s where Locate is operating from stale data. If heartbeat could send an unhealthy signal to Locate for all services it tracks in a pod, then we could reduce possible downtime a good deal on reboot events.

@cristinaleonr: what do you think?

**Comment by cristinaleonr** [comment]
Sounds good to me. The Locate refreshes its data from Memorystore every 10 seconds, so there will still be a 10 second delay for all the instances to get the event.

**Comment by nkinkade** [comment]
This was done in PR #141 . Thank you, @cristinaleonr!
