### ISSUE TITLE
When `site=` query parameter is passed, ignore probability settings

### ISSUE THREAD

**Issue by nkinkade** [m-lab/locate#142]
When looking over [a problem we were having with mlab3-lis01](https://github.com/m-lab/ops-tracker/issues/1800) with @stephen-soltesz, we were at first confused that Locate was sometimes returning a 500 response:

https://locate.measurementlab.net/v2/nearest/ndt/ndt7?site=lis01

It turns out it is because lis01 is a 1g site with only 50% probability.  When the query parameter `site=` is present, Locate should probably ignore the site's probability configuration.

**Comment by nkinkade** [comment]
I believe this was resolved with the merge of PR #148.  Closing.

**Comment by cristinaleonr** [comment]
Yes, it was resolved.
