### ISSUE TITLE
Enable Cross-Origin Resource Sharing headers

### ISSUE THREAD

**Issue by pboothe** [m-lab/locate#15]
CORS allows third party websites to be sure they are allowed to use the resources served by locate.measurementlab.net.  We enabled this in mlab-ns via: https://github.com/m-lab/mlab-ns/search?q=Access-Control-Allow-Origin%3A&unscoped_q=Access-Control-Allow-Origin%3A

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/587
