### ISSUE TITLE
Request for correction of IP geolocation

### ISSUE THREAD

**Issue by critzo** [m-lab/locate#27]
A city in Iowa reports that their users are incorrectly geolocated to India on its IP block: 199.115.180.0 - 199.115.180.255. 
![image](https://user-images.githubusercontent.com/4633345/90541466-ad56c680-e150-11ea-9c70-8ca3900824f8.png)

User emailed support requesting that we update our records. This is obviously an issue in Google's geolocation provided through the Locate service. Is there a better way to report this to be corrected by Google than logging an issue here?

**Comment by laiyi-ohlsen** [comment]
@critzo can you check if this is resolved?

**Comment by critzo** [comment]
ipinfo.io and Whois both list these IP blocks as belonging to the city of Decorah, IA. If there is a way to test AppEngine's geolocation of an IP address, we can test that, but I'm not aware of such a tool. This combined with the [fallback option that was added to Locate](https://github.com/m-lab/locate/pull/29) as a result of this issue should be enough to consider this closed.
