### ISSUE TITLE
Brazil ISP reports incorrect geo for Google Search ndt integration

### ISSUE THREAD

**Issue by critzo** [m-lab/locate#30]
Contact details and ISP are in their email to support@measurementlab.net

> Hello,
> 
> We are Internet Service Provider in Brazil and we have one issue with
> Google speed test.
> When the tests are made by url https://speed.measurementlab.net/#/ they
> are ok! The selected server for tests was in São Paulo with about 20ms 
> of latency.
> When the tests are made by url
> https://www.google.com/search?sxsrf=ALeKk01BD6OwQuWI7lh8ClKrfaIC0xQCfg%3A1598375030608&source=hp&ei=dkRFX6W5IvW95OUP0sKn8Ak&q=run+speed+test&oq=run+&gs_lcp=CgZwc3ktYWIQAxgAMgQIIxAnMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQILhBDMgQIABBDMgQILhBDMgQIABBDMgQIABBDOgoILhDHARCvARAnOgUIABCRAjoCCC46AggAUKwLWMYPYLcaaABwAHgAgAGiA4gB3wuSAQUzLTMuMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab
> , we have problems.
> The selected server for tests was in Lagos, sometimes in Nairobi with
> latency greater than 200ms.
> Can you help us?
> 
>

**Comment by stephen-soltesz** [comment]
I just tagged https://github.com/m-lab/locate/releases/tag/v0.4.0 to include additional fallback options when AppEngine does not provide accurate latitude/longitude values.

**Comment by critzo** [comment]
Super. Thanks @stephen-soltesz. I've informed them and asked them to confirm the fix.

**Comment by stephen-soltesz** [comment]
@critzo the locate api now explicitly returns headers that indicate how it made the decision it made.

```
curl --dump-header - https://locate.measurementlab.net/v2/nearest/ndt/ndt7
HTTP/1.1 200 OK
Date: Tue, 25 Aug 2020 17:58:11 GMT
Content-Type: application/json
...
X-Locate-Clientlatlon: 40.712775,-74.005973
X-Locate-Clientlatlon-Method: appengine-latlong
```

The `X-Locate-Clientlatlon` is the actual lat/lon location it used.
The `X-Locate-Clientlatlon-Method` is how it got that lat lon.

These should be helpful for future debugging and verification.

**Comment by critzo** [comment]
User reports that this is now resolving location correctly for them. Success @stephen-soltesz !
