### ISSUE TITLE
User reports of Cloud VMs without geo location headers to Locate API

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/locate#40]
When the Locate API does not receive any location headers from App Engine, the request fails with 503.

The country fallback helped https://github.com/m-lab/locate/pull/29 , however we should consider adding a third-party geoip database as a final fallback, e.g. geolite2 used by uuid-annotator.

**Comment by pboothe** [comment]
Consider adding "choose a random healthy server somewhere in the world" as a final fallback method.  If we can't geolocate the user, that seems like our problem not theirs, so returning an error code feels like giving up on a valid user request.

**Comment by critzo** [comment]
If we do decide to use a third party service for this, I suggest that we consider options other than geolite2 as well. We should evaluate it's accuracy compared to other services like ipinfo.io, with whom we already have collaborated. I think we'll find that it is much more accurate than maxmind.

**Comment by stephen-soltesz** [comment]
@pboothe there appear to be two default positions to this situation.

1. "Clearly" the server should return random results if it cannot make a better determination
2. "Clearly" random results from the server are not what a user or M-Lab want

I brought this question to the team at one of the engineering discussion meetings. No one spoke in defense of the random response. The rationale being:

* A random target server will not perform well or consistently
* A random target server will not provide a user with helpful information about their connectivity
* A random target server will not provide helpful measurement data for M-Lab
* A random target server masks an underlying issue
* A random target server is not consistent with the Locate API's "/v2/nearest" query

In this case, a user reported the problem because it wasn't working at all. And, we can add a better strategy. It's not clear to me that this would have happened with random results.

**Comment by stephen-soltesz** [comment]
@critzo There is already support using geolite2 in the queue. However, we're creating an architecture that would make it very simple to add other sources too, like ipinfo.io. In general, it would be preferable perform target selection using the same client geo as we use to annotate the data. There's a lot here of course. So, I'm not saying anything is set in stone.

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/locate/releases/tag/v0.7.0
